# Generated by Django 3.0.4 on 2021-01-16 01:10

import core.erp.validators
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, verbose_name='Nombres')),
                ('surnames', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('dni', models.CharField(max_length=10, unique=True, validators=[core.erp.validators.vcedula], verbose_name='Cédula')),
                ('date_birthday', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección')),
                ('gender', models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino')], default='male', max_length=10, verbose_name='Sexo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=10, validators=[core.erp.validators.vcedula], verbose_name='Cédula')),
                ('names', models.CharField(max_length=150, verbose_name='Nombres')),
                ('direccion', models.CharField(max_length=150, verbose_name='Direccion')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Client')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('uMedida', models.CharField(choices=[('libras', 'libras'), ('litros', 'Litros'), ('Costales', 'Costal'), ('kilos', 'Kilos'), ('gramos', 'gramos')], default='libra', max_length=10, verbose_name='Unidad de Medida')),
                ('cant', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad')),
                ('date_add', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de Creación')),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripcion')),
                ('prov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Suppliers', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Materia Prima',
                'verbose_name_plural': 'Materia Prima',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, upload_to='product/%Y/%m/%d', verbose_name='Imagen')),
                ('stock', models.IntegerField(blank=True, default=0, null=True)),
                ('pvp', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, validators=[core.erp.validators.validacionCantidad], verbose_name='Precio de venta')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cant', models.IntegerField(default=0, validators=[core.erp.validators.validacionCantidad])),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Sale')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalle de Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CargarRawMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(blank=True, default=1, null=True, validators=[core.erp.validators.validacionCantidad])),
                ('fechaIngreso', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de Ingreso')),
                ('date_ven', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Vencimiento')),
                ('observacion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Observacion')),
                ('materiaPrima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.RawMaterial')),
            ],
        ),
        migrations.CreateModel(
            name='CargarProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(blank=True, default=1, null=True, validators=[core.erp.validators.validacionCantidad], verbose_name='Cantidad (Unidad)')),
                ('fechaIngreso', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de Ingreso')),
                ('date_ven', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Vencimiento')),
                ('observacion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Observacion')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Product', verbose_name='Producto')),
            ],
        ),
    ]
