# Generated by Django 3.0.4 on 2021-01-11 19:52

import core.erp.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=10, validators=[core.erp.validators.vcedula], verbose_name='Cédula')),
                ('names', models.CharField(max_length=150, verbose_name='Nombres')),
                ('direccion', models.CharField(max_length=150, verbose_name='Direccion')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripcion')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Cantidad')),
                ('prov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Suppliers', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Materia Prima',
                'verbose_name_plural': 'Materia Prima',
                'ordering': ['id'],
            },
        ),
    ]
