# Generated by Django 3.0.4 on 2021-01-11 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_rawmaterial_suppliers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterial',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='cant',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='date_add',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='date_ven',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Vencimiento'),
        ),
    ]
