# Generated by Django 3.0.4 on 2021-01-11 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_auto_20210111_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='uMedida',
            field=models.CharField(choices=[('libra', 'lb'), ('litro', 'L'), ('Costal', 'Costal')], default='libra', max_length=10, verbose_name='Unidad de Medida'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='date_add',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de Creación'),
        ),
    ]
