# Generated by Django 3.0.4 on 2021-01-11 23:09

import core.erp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_auto_20210111_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='cant',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[core.erp.validators.validacionCantidad], verbose_name='Cantidad'),
        ),
    ]
