# Generated by Django 3.0.4 on 2021-01-11 23:15

import core.erp.validators
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_auto_20210111_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargarRawMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(blank=True, default=0, null=True, validators=[core.erp.validators.validacionCantidad])),
                ('fechaIngreso', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de Ingreso')),
                ('observacion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Observacion')),
                ('materiaPrima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.RawMaterial')),
            ],
        ),
    ]
