# Generated by Django 3.0.4 on 2021-01-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_cargarrawmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='cant',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='uMedida',
            field=models.CharField(choices=[('libras', 'lb'), ('litros', 'L'), ('Costales', 'Costal')], default='libra', max_length=10, verbose_name='Unidad de Medida'),
        ),
    ]
